config/routes.rb
Rails.application.routes.draw do
  get 'hometasks/create'

  resources :homes, only: :index do
    resources :tasks, only: :index do
      resources :hometasks, only: [:create, :destroy]
    end
  end
  resources :tasks, only: :index

  resources :hometasks, only: :index

  root to: 'homes#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

# do
#     resources :hometasks, only: :create
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :hometasks
  has_many :tasks, through: :hometasks
  has_many :users, through: :hometasks
end

app/models/hometask.rb
class Hometask < ApplicationRecord
  belongs_to :user
  belongs_to :task
  belongs_to :home
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :hometasks
  has_many :users, through: :hometasks
  has_many :homes, through: :hometasks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hometasks
  has_many :tasks, through: :hometasks
  has_many :homes, through: :hometasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @homes = Home.all
  end
end

app/controllers/hometasks_controller.rb
class HometasksController < ApplicationController
before_action :authenticate_user!

  def create
    @home = Home.find(params[:home_id])
    @task = Task.find(params[:task_id])
    @hometask = Hometask.new(home: @home, task: @task, user: current_user, done: true)
    if @hometask.save
      redirect_to  home_tasks_path(@home), notice: 'La tarea ha sido realizada'
    else
      redirect_to  home_tasks_path(@home), alert: 'La tarea no se ha realizado'
    end
  end

  def index
    @hometasks = current_user.hometasks.order('created_at DESC')
  end

  def destroy
    @home = Home.find(params[:home_id])
    @task = Task.find(params[:task_id])
    @hometask = Hometask.find_by(home: @home, task: @task, user: current_user)
    @hometask.destroy
    redirect_to  home_tasks_path(@home), alert: 'La tarea ha sido eliminada'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @home_id = Home.find(params[:home_id])
    @task_id = Home.find(params[:home_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/hometasks_helper.rb
module HometasksHelper
  def mismo_home?(task)
     e = task.hometasks.where(user_id: current_user.id, home_id: @home_id)
     if e.count > 0
       true
     else
       false
     end
 end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/homes/index.html.erb
<div class="container">
  <div class="row">
    <% @homes.each_slice(3) do |row| %>
      <% row.each do |home| %>
        <div class="col-md-3 my-3">
          <div class="card">
            <%= image_tag home.photo, class:'card-img-top img-fluid' %>
            <div class="card-body">
              <h5 class="card-title text-center"><%= home.address %></h5>
            </div>
            <div class="card-footer">
              <% if user_signed_in? %>
                <%= link_to "Ver tareas", home_tasks_path(home), class: 'btn btn-success btn-block'%>
              <% else %>
                <a class="btn btn-primary btn-block" href="<%= new_user_session_path %>"> Registrese <span class="sr-only">(current)</span></a>
              <% end %>
            </div>
          </div>
        </div>
       <% end %>
     <% end %>
  </div>
</div>

app/views/hometasks/create.html.erb
<h1>Hometasks#create</h1>
<p>Find me in app/views/hometasks/create.html.erb</p>

app/views/hometasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="container">
      <table class="table">
        <h2>Tareas realizadas</h2>
        <thead>
          <tr>
            <th scope="col">Casa</th>
            <th scope="col">Tarea</th>
            <th scope="col">Fecha</th>
          </tr>
        </thead>
        <tbody>
          <% @hometasks.each do |hometask| %>
            <tr>
              <td><%= hometask.home.address %></td>
              <td><%= hometask.task.name %></td>
              <td><%= time_ago_in_words(hometask.created_at) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">APP Limpieza</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <a class="nav-link" href="<%= homes_path %>">Casas <span class="sr-only">(current)</span></a>
        <a class="nav-link" href="<%= hometasks_path %>">Tareas Realizadas <span class="sr-only">(current)</span></a>
      <% else %>
      <% end %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>
           <%= current_user.email %>
          <% else %>
           Ingreso
          <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <% if user_signed_in? %>
              <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="DELETE">Salir</a>
          <% else %>
            <a class="dropdown-item" href="<%= new_user_session_path %>">Ingreso</a>
            <a class="dropdown-item" href="<%= new_user_registration_path %>">Registro</a>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vacasa</title>
    <%= csrf_meta_tags %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- javascript-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
      <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
      <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
        <% @tasks.each_slice(3) do |row| %>
            <% row.each do |task| %>
              <div class="col-md-3 my-3">
                <div class="card">
                  <%= image_tag task.photo, class:'card-img-top img-fluid' %>
                  <div class="card-body">
                    <h5 class="card-title text-center"><%= task.name %></h5>
                    <% if mismo_home?(task) %>
                      <p class="text-center">Presione para deshacer la tarea</p>
                      <%= link_to "Borrar", home_task_hometask_path(@home_id, task, current_user), class: 'btn btn-danger btn-block', method: :delete%>
                    <% else %>
                    <p class="text-center">Presione para marcar como listo</p>
                      <%= link_to "Realizar", home_task_hometasks_path(@home_id, task), class: 'btn btn-success btn-block', method: :post%>
                    <% end %>
                  </div>
                </div>
              </div>
             <% end %>
         <% end %>
  </div>
</div>